name          'wirbelsturm-mosquitto'
version       '0.0.1'
source        'https://github.com/lowi-yeah/puppet-mosquitto.git'
author        'Stephan \'lowi\' Lohwasser'
license       'Apache License, Version 2.0'
summary       'Module for managing and configuring Mosquitto MQTT Broker'
description   'Module for managing and configuring Mosquitto MQTT Broker'
project_page  'https://github.com/lowi-yeah/puppet-mosquitto'
#DISABLED UNTIL PUBLISHED ON PUPPETFORGE#dependency 'miguno/puppet-limits'
#DISABLED UNTIL PUBLISHED ON PUPPETFORGE#dependency 'miguno/puppet-supervisor'
#DISABLED SO WE DO NOT DEPEND ON PUPPETFORGE#dependency    'puppetlabs/stdlib', '>= 4.1.0'
